<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.smartlink</groupId>
        <artifactId>smartlink-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>smartlink-server</artifactId>

    <description>
        业务模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-mail</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-idempotent</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-mongo</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-log</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-excel</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-ratelimiter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-translation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-sensitive</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-encrypt</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-system</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>3.0.0-RC1</version>
        </dependency>
        <dependency>
            <groupId>me.zhyd.oauth</groupId>
            <artifactId>JustAuth</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>core</artifactId>
            <version>3.4.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
            <version>3.4.1</version>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itextpdf</artifactId>
            <version>5.5.13.3</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>2.0.27</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.14</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
            <version>1.24</version>
        </dependency>
        <dependency>
            <groupId>com.aspose</groupId>
            <artifactId>aspose-words</artifactId>
            <version>${words.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aspose</groupId>
            <artifactId>aspose-pdf</artifactId>
            <version>${pdf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aspose</groupId>
            <artifactId>aspose-cells</artifactId>
            <version>${cells.version}</version>
        </dependency>
        <dependency>
            <groupId>com.aspose</groupId>
            <artifactId>aspose.slides</artifactId>
            <version>${slides.version}</version>
        </dependency>
        <dependency>
            <groupId>org.ofdrw</groupId>
            <artifactId>ofdrw-converter</artifactId>
            <version>2.3.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
        </dependency>

        <!--授权证书-->
        <dependency>
            <groupId>de.schlichtherle.truelicense</groupId>
            <artifactId>truelicense-core</artifactId>
            <version>1.33</version>
        </dependency>
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>6.2.2</version>
        </dependency>
        <!--图片压缩-->
        <dependency>
            <groupId>net.coobird</groupId>
            <artifactId>thumbnailator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty-http</artifactId>
            <version>1.0.25</version>
        </dependency>

        <dependency>
            <groupId>com.qiniu</groupId>
            <artifactId>qiniu-java-sdk</artifactId>
            <version>7.9.3</version>
        </dependency>

        <dependency>
            <groupId>com.github.tobato</groupId>
            <artifactId>fastdfs-client</artifactId>
            <version>1.26.2</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.39</version>
        </dependency>

        <!--税务云使用-->
        <!-- jjwt，Java Web Token签名工具包 -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.6.0</version>
        </dependency>

        <!--JWT令牌依赖-->
<!--        <dependency>-->
<!--            <groupId>io.jsonwebtoken</groupId>-->
<!--            <artifactId>jjwt</artifactId>-->
<!--            <version>0.9.1</version>-->
<!--        </dependency>-->

        <!--jdk9以后需添加此依赖-->
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>


        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-spring-boot-starter-jaxws</artifactId>
        </dependency>

        <!-- webflux -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <version>2.6.6</version>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
            <version>2.6.2</version>
        </dependency>
        <!-- 文档转换 -->
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>3.0.0-RC1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </dependency>
        <!--okHTTP -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
        </dependency>

    </dependencies>

</project>
