### Send a form with the text and file fields
POST http://127.0.0.1:8080/server/businessDocument/selectHotData
Content-Type: application/x-www-form-urlencoded

###
POST http://127.0.0.1:8080/auth/thirdParty/login
Content-Type: application/json

{
  "clientId": "e5cd7e4891bf95d1d19206ce24a7b32e",
  "userId": "1",
  "sign": "5bGV56S6"
}

###
POST http://127.0.0.1:8080/archive/collection/page?pageNum=1&pageSize=20
Content-Type: application/json

{
    "clientId": "e5cd7e4891bf95d1d19206ce24a7b32e",
    "userId": "1",
    "sign": "5bGV56S6"
}



###
GET http://104.200.100.160:30085/api/data/platform/org/dept/list
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXBpIl0sImNvcnBJZCI6bnVsbCwidXNlcl9pZCI6IjQwNWU1MjRkMDNhMTRkMDJhZGRlZmIxN2FjYzAzNTNiIiwidXNlcl9uYW1lIjoiemhhbmdqaWFsaW5nIiwic2NvcGUiOlsicmVhZCJdLCJtb2JpbGUiOmZhbHNlLCJpc0FkbWluIjp0cnVlLCJleHAiOjE3NjQ5MzI2ODUsImlzQXBwQWRtaW4iOmZhbHNlLCJhdXRob3JpdGllcyI6WyJVU0VSIiwiQVVUSF9TWVNURU1fTUFOQUdFIl0sImp0aSI6ImU3MDJhMTZlLWIxMDItNGNjZi1iM2NjLTc4ZGI1NDc4MzU4OSIsImNsaWVudF9pZCI6ImFwaSJ9.UwGfDR16t9D0EKDfDJzvAzZiakE1MR0lxYKrVd1iQwMas4nzryygen1JlOvgBrNRUwu0-V68-yDr-tAuSOGH6hm_TZ1SI3XAP7MJq7iYYcziq2LJep1n5Sf_ngvLw-00lqbucsgQyBjWblMPL510XhOlukzTw64h-FOfknrHgvk
X-System-Code: DZKJDA_SYSTEM


###
GET http://211.159.156.229:6006/usap/login
Content-Type: application/x-www-form-urlencoded

###
GET http://127.0.0.1:8080/system/examineApprove/treeNode
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiJHdndYOEpGY1Baa1NNRGdIVjFsSW1IcVBVWnVuUEtUdyIsImNsaWVudGlkIjoiZTVjZDdlNDg5MWJmOTVkMWQxOTIwNmNlMjRhN2IzMmUiLCJ0ZW5hbnRJZCI6IjAwMDAwMCIsInVzZXJJZCI6MSwidXNlck5hbWUiOiJhZG1pbiIsImRlcHRJZCI6IjEwMyIsImRlcHROYW1lIjoi5byA5Y-R5rWL6K-VIiwiZGVwdENhdGVnb3J5IjoiMyJ9.XdClA0BffWzkuV53GjzrjZxyu6wPEqfzcJGwLj76Ba0
clientid: e5cd7e4891bf95d1d19206ce24a7b32e

###
POST http://127.0.0.1:8080/archive/collection/batchCommit
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiJHdndYOEpGY1Baa1NNRGdIVjFsSW1IcVBVWnVuUEtUdyIsImNsaWVudGlkIjoiZTVjZDdlNDg5MWJmOTVkMWQxOTIwNmNlMjRhN2IzMmUiLCJ0ZW5hbnRJZCI6IjAwMDAwMCIsInVzZXJJZCI6MSwidXNlck5hbWUiOiJhZG1pbiIsImRlcHRJZCI6IjEwMyIsImRlcHROYW1lIjoi5byA5Y-R5rWL6K-VIiwiZGVwdENhdGVnb3J5IjoiMyJ9.XdClA0BffWzkuV53GjzrjZxyu6wPEqfzcJGwLj76Ba0
clientid: e5cd7e4891bf95d1d19206ce24a7b32e

{"ids":["697aeb8abfd03270bb7a0a21","697aeb8abfd03270bb7a0a22"],"treeId":""}

### 101,30，1，2
GET http://127.0.0.1:8080/system/examineApprove/list?pageNum=1&pageSize=20&filedValue=pending
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiJHdndYOEpGY1Baa1NNRGdIVjFsSW1IcVBVWnVuUEtUdyIsImNsaWVudGlkIjoiZTVjZDdlNDg5MWJmOTVkMWQxOTIwNmNlMjRhN2IzMmUiLCJ0ZW5hbnRJZCI6IjAwMDAwMCIsInVzZXJJZCI6MSwidXNlck5hbWUiOiJhZG1pbiIsImRlcHRJZCI6IjEwMyIsImRlcHROYW1lIjoi5byA5Y-R5rWL6K-VIiwiZGVwdENhdGVnb3J5IjoiMyJ9.XdClA0BffWzkuV53GjzrjZxyu6wPEqfzcJGwLj76Ba0
clientid: e5cd7e4891bf95d1d19206ce24a7b32e


###
POST http://127.0.0.1:8080/workflow/task/completeTask
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiIxQTZrb0RoeWwwQkE0YW1wOHpKeE9mWWhXYnJPUmRQMSIsImNsaWVudGlkIjoiZTVjZDdlNDg5MWJmOTVkMWQxOTIwNmNlMjRhN2IzMmUiLCJ0ZW5hbnRJZCI6IjAwMDAwMCIsInVzZXJJZCI6MSwidXNlck5hbWUiOiJhZG1pbiIsImRlcHRJZCI6MTAzLCJkZXB0TmFtZSI6IueglOWPkemDqOmXqCIsImRlcHRDYXRlZ29yeSI6IiJ9.pZn6lbdikqsj4FVxGbO1tlP31kXOqmraqrdP6mYwzUQ
clientid: e5cd7e4891bf95d1d19206ce24a7b32e

{
    "taskId": "2017136055021572114",
    "variables": {"amount": 1234},
    "messageType": ["1"],
    "wfCopyList": [],
    "fileId": [],
    "taskVariables": {
        "entity": {
            "id": "2017136053293518850",
            "fromId": "1937034144613277697",
            "fromManageId": "1937034144613277697",
            "fromName": "新测试",
            "fromType": "ce_bx",
            "dataChannel": "pc",
            "categoryId": "1937025173462589441",
            "categoryName": "新测试",
            "categoryType": "new_ceshi",
            "consumptionDetails": "{}",
            "status": "draft",
            "remark": "",
            "createDept": 103,
            "createBy": 1,
            "createTime": "2026-01-30 15:21:26",
            "updateBy": 1,
            "updateTime": "2026-01-30 15:21:26",
            "detailsData": "[{\"key\":\"defaultKey\",\"type\":\"uploadInvoice\",\"value\":[]}]",
            "receiptUrl": null,
            "auditDetail": "{\"ICBC\":2134}"
        },
        "userList": ["1", "3"],
        "userList2": ["1", "3"]
    }
}


###
POST http://127.0.0.1:8080/workflow/processInstance/getHistoryRecord/exportPdf
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiIxQTZrb0RoeWwwQkE0YW1wOHpKeE9mWWhXYnJPUmRQMSIsImNsaWVudGlkIjoiZTVjZDdlNDg5MWJmOTVkMWQxOTIwNmNlMjRhN2IzMmUiLCJ0ZW5hbnRJZCI6IjAwMDAwMCIsInVzZXJJZCI6MSwidXNlck5hbWUiOiJhZG1pbiIsImRlcHRJZCI6MTAzLCJkZXB0TmFtZSI6IueglOWPkemDqOmXqCIsImRlcHRDYXRlZ29yeSI6IiJ9.pZn6lbdikqsj4FVxGbO1tlP31kXOqmraqrdP6mYwzUQ
clientid: e5cd7e4891bf95d1d19206ce24a7b32e

[
    "2017136053293518850"
]


