<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.smartlink</groupId>
        <artifactId>smartlink-common</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>smartlink-common-entity</artifactId>

    <description>
        smartlink-common-entity 业务实体
    </description>

    <dependencies>

        <!-- 租户模块 -->
        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-tenant</artifactId>
        </dependency>

        <!-- 数据库服务 -->
        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-excel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.smartlink</groupId>
            <artifactId>smartlink-common-check</artifactId>
            <version>5.2.3</version>
        </dependency>

    </dependencies>

</project>
